#ifndef FLAGS_H

#define PREPROC_SWAP_SEQ 1
#define PREPROC_SWAP_BATCH 1
#define PREPROC_SWAP_BOTH 1
#define PREPROC_EBSR_BOTH 1
#define PREPROC_EBSR_SEQ 1
#define PREPROC_EBSR_BATCH 1
#define PREPROC_EFSR_BOTH 1
#define PREPROC_EFSR_SEQ 1
#define PREPROC_EFSR_BATCH 1
#define PREPROC_TWO_OPT 1
#define PREPROC_DIVERSIFICATION 1
#define PREPROC_FIRST_IMPROVE 1
#define PREPROC_LOGICAL_TABU 1

#endif // FLAGS_H
